### PR TITLE
update for xarray new map_index_queries

### LINKED ISSUE #77: Python 3.8 `ioos_qc` leads to an ImportError with xarray, but Python 3.7 does not.
```
mamba create --name test-xarray-ioosqc38 python=3.8 xarray ioos_qc
conda activate test-xarray-ioosqc38
```
and then in a python window trying:
```
from ioos_qc.streams import NumpyStream
```
gives
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kthyng/miniconda3/envs/test-xarray-ioosqc/lib/python3.8/site-packages/ioos_qc/streams.py", line 10, in <module>
    from xarray.core.indexing import remap_label_indexers
ImportError: cannot import name 'remap_label_indexers' from 'xarray.core.indexing' (/Users/kthyng/miniconda3/envs/test-xarray-ioosqc/lib/python3.8/site-packages/xarray/core/indexing.py)
```

However, the following environment with Python 3.7 does not lead to an error:
```
mamba create --name test-xarray-ioosqc37 python=3.7 xarray ioos_qc
```

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes #77 

@kwilcox any chance this will get me some credit and a review on #71 and #75  :stuck_out_tongue_winking_eye:

### CODE REVIEW

**Comment by ocefpaf** [comment]
This PR makes it py>=38 only. I can push and alternative that makes it py>=36 if you think it is useful.

**Comment by kthyng** [comment]
@ocefpaf including Python 3.7 would be useful for me

**Comment by ocefpaf** [comment]
> @ocefpaf including Python 3.7 would be useful for me

Latest commit re-adds it. I added some comments on the code that needs to be removed when dropping 3.7

**Comment by kwilcox** [comment]
:laughing: on a random computer without `pre-commit` installed. The shame I feel is immense.

**Pull request merged**
