### PR TITLE
provision-with-micromamba is deprecated

### PR DESCRIPTION
**Pull request by ocefpaf**
Using mamba-org/setup-micromamba@v1 instead.

### CODE REVIEW

**Comment by ocefpaf** [comment]
All the tests that use `numba` and masked arrays are failing. In a way, they were probably wrong before even when they passed b/c `numba` doesn't support masked arrays. xref.: https://github.com/numba/numba/issues/1834

Ideally we should fix the tests but we can pin to `numba<0.57` to restore the old behavior.

**Comment by ocefpaf** [comment]
@kwilcox I'm not sure pinning to an old numba is the best course of action here. What do you think? I would just fail,for now, when masked array are used with numba, until numba supports them properly.

**Comment by ocefpaf** [comment]
@srstsavage and @kthyng I'm self-merging this one to move things forward. Note that we have a pin on numba that limits `ioos_qc` use with Python >=3.11. I'll investigate that but for now we should issue a new release to prevent folks from installing it with an unpinned numba.

PS: I also fixed some tz-aware date comparisons by making all the tests tz-naive. We should add specific tz-aware tests though in the future.

**Comment by srstsavage** [comment]
@ocefpaf :+1: thank you!

**Pull request merged**
